language: python
python:
  - 2.7
sudo: false
cache:
  directories:
    - eggs
env:
  - PLONE_VERSION=4.1
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
matrix:
  exclude:
    - python: 2.7
      env: PLONE_VERSION=4.1
    - python: 2.6
      env: PLONE_VERSION=4.2
    - python: 2.6
      env: PLONE_VERSION=4.3
    - python: 2.6
      env: PLONE_VERSION=5.0
  allow_failures:
    - env: PLONE_VERSION=5.0
  fast_finish: true
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - sed -ie "s#versions-$PLONE_VERSION.x#versions#" travis.cfg
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - pip install zc.buildout
  - buildout -c travis.cfg annotate
  - buildout -c travis.cfg -N -q
branches:
  only:
    - master
script:
  - bin/code-analysis
  - bin/test
notifications:
  hipchat:
    secure: "CIlnP9L4dtE67sp8WVMTBCb5/vvqhQDqa6IrQG1KX0LsI+y/7CORiF8fOQI6mbRa/dMXMEYUgfF1mYd0VknmVSsKglMpeUNvkcUzMtSQjM1gVegBEk1LbAvuQOAtE+xsDeYzwERDFoDPcAeLHWumEi2zcKbOOsXLxjqSekggulE="
