language: python
python:
  - 2.7
env:
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -N -t 5 -c travis.cfg
branches:
  only:
    - master
script: bin/test
notifications:
  irc: irc.freenode.org#propertyshelf
  hipchat:
    secure: "CIlnP9L4dtE67sp8WVMTBCb5/vvqhQDqa6IrQG1KX0LsI+y/7CORiF8fOQI6mbRa/dMXMEYUgfF1mYd0VknmVSsKglMpeUNvkcUzMtSQjM1gVegBEk1LbAvuQOAtE+xsDeYzwERDFoDPcAeLHWumEi2zcKbOOsXLxjqSekggulE="
